
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  postgres:
    image: postgres:15
    ports:
       - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    command: >
      postgres
      -c wal_level=logical
      -c max_replication_slots=4
      -c max_wal_senders=4


  connect:
    image: debezium/connect:2.5
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      PLUGIN_PATH: /kafka/connect
      POSTGRES_HOST: postgres
    depends_on:
      - kafka
      - postgres

  opensearch:
    image: opensearchproject/opensearch:2.13.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=@K69A3%wZx
    ports:
      - "9200:9200"

  flink-jobmanager:
    image: flink:1.19
    command: ["/bin/bash", "/jobmanager-entrypoint.sh"]
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    volumes:
      - ./flink/sql:/opt/flink/sql
      - ./flink/lib/ext:/opt/flink/lib/ext
      - ./flink/jobmanager-entrypoint.sh:/jobmanager-entrypoint.sh
    depends_on:
      - kafka

  flink-taskmanager:
    image: flink:1.19
    command: ["/bin/bash", "/taskmanager-entrypoint.sh"]
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=2
    volumes:
      - ./flink/lib/ext:/opt/flink/lib/ext
      - ./flink/taskmanager-entrypoint.sh:/taskmanager-entrypoint.sh
    depends_on:
      - flink-jobmanager

  flink-sql-client:
    image: flink:1.19
    command: /bin/bash
    stdin_open: true
    tty: true
    depends_on:
      - flink-jobmanager
    profiles:
      - sql-client

